maxblog/apps/feedback/urls.py
from django.urls import path
from . import views


app_name = 'feedback'

urlpatterns = [
    path('', views.feedback, name='feedback'),
]

maxblog/apps/posts/urls.py
from django.urls import path, include
from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.SearchPostsView.as_view(), name='post_list'),
    path('post/<int:pk>/', views.post_details, name='post_details'),
    path('search/', views.SearchPostsView.as_view(), name='search_posts'),
    path('post/new', views.post_new, name='post_new'),
]

maxblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('feedback/', include('feedback.urls')),
    path('', include('posts.urls')),
]

maxblog/apps/feedback/models.py
from django.db import models
from django.template.defaultfilters import truncatechars


class Feedback(models.Model):
    author_email = models.EmailField()
    text = models.TextField()

    @property
    def short_text(self):
        return truncatechars(self.text, 100)

    def __str__(self):
        return self.text

maxblog/apps/posts/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.template.defaultfilters import truncatechars


class Section(models.Model):
    """
    The topic section to which the Post may relate
    """
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class PostAuthor(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):
    authors = models.ManyToManyField(PostAuthor)
    title = models.CharField(max_length=100)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    tags = models.ManyToManyField(Tag)
    section = models.ForeignKey(Section, on_delete=models.CASCADE)

    @property
    def short_text(self):
        return truncatechars(self.text, 100)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author_name = models.CharField(max_length=100)
    text = models.TextField()

    @property
    def short_text(self):
        return truncatechars(self.text, 100)

    def __str__(self):
        return self.author_name

maxblog/apps/feedback/forms.py
from django.forms import ModelForm
from .models import Feedback


class FeedbackForm(ModelForm):
    class Meta:
        model = Feedback
        fields = ['author_email', 'text']
        labels = {
            'author_email': 'Your email',
            'text': 'Your feedback'
        }

maxblog/apps/posts/forms.py
from django.forms import forms, ModelForm

from .models import Comment, Post


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['author_name', 'text']
        labels = {
            'author_name': 'Your name',
            'text': 'Comment'
        }


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['authors', 'title', 'text', 'tags', 'section']
        labels = {
            'authors': 'Post authors',
            'title': 'Post title',
            'text': 'Post text',
            'tags': 'Post tags',
            'section': 'Post section',
        }

maxblog/apps/feedback/views.py
from django.shortcuts import render
from .forms import FeedbackForm
from django.shortcuts import redirect


def feedback(request):
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid:
            form.save(commit=True)
            return redirect('/')
    else:
        form = FeedbackForm()
    return render(request, 'feedback/feedback.html', {'form': form})

maxblog/apps/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView
from django.db.models import Q
from django.utils import timezone
from .models import Post
from .forms import CommentForm, PostForm


def post_details(request, pk):
    post = get_object_or_404(Post, pk=pk)
    comments = post.comment_set.order_by('id')
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid:
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('posts:post_details', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'posts/post_details.html', {'post': post, 'comments': comments, 'form': form})


class SearchPostsView(ListView):
    model = Post
    template_name = 'posts/post_list.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        author = self.request.GET.get('author')
        tag = self.request.GET.get('tag')
        section = self.request.GET.get('section')

        object_list = Post.objects.order_by('-created_date')

        if query:
            object_list = object_list.filter(
                Q(title__icontains=query) | Q(authors__name__icontains=query)).distinct()
        if author:
            object_list = object_list.filter(
                Q(authors__name__icontains=author))
        if tag:
            object_list = object_list.filter(
                Q(tags__name__icontains=tag))
        if section:
            object_list = object_list.filter(
                Q(section__name__icontains=section))

        return object_list


def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid:
            post = form.save(commit=False)
            post.created_date = timezone.now()
            post.save()
            form.save_m2m()
            return redirect('posts:post_details', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'posts/post_new.html', {'form': form})

maxblog/templates/base.html
<!doctype html>

<html lang="en">

<head>
    <title>{% block title %}MaxBlog{% endblock title %}</title>
</head>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<body class="d-flex flex-column h-100" data-gr-c-s-loaded="true">
    <header>
        <!-- Fixed navbar -->
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <a class="navbar-brand" href="/">MaxBlog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'feedback:feedback' %}">Feedback<span
                                class="sr-only">(current)</span></a>
                    </li>
                    {% block navbar_list_items %}
                    {% endblock navbar_list_items %}
                </ul>
                {% block navbar_content %}
                {% endblock navbar_content %}
            </div>
        </nav>
    </header>

    <main role="main" class="flex-shrink-0" style="padding-top: 60px;">
        <div>
            {% block content %}
            {% endblock %}
        </div>
    </main>
</body>

</html>

maxblog/templates/feedback/feedback.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}Feedback{% endblock title %}

{% block content %}
<div style="padding: 32px; padding-top: 16px;">
    {% with submit_btn_text="Send feedback" %}
        {% include 'form.html' %}
    {% endwith %}
</div>
{% endblock %}

maxblog/templates/form.html
{% load widget_tweaks %}

<form method="POST" class="post-form" style="padding-top: 16px;">
    {% csrf_token %}

    {% for hidden_field in form.hidden_fields %}
        {{ hidden_field }}
    {% endfor %}

    {% if form.non_field_errors %}
        <div class="alert alert-danger" role="alert">
            {% for error in form.non_field_errors %}
                {{ error }}
            {% endfor %}
        </div>
    {% endif %}

    {% for field in form.visible_fields %}
        <div class="form-group">
            {{ field.label_tag }}
            {% if form.is_bound %}
                {% if field.errors %}
                    {% render_field field class="form-control is-invalid" %}
                    {% for error in field.errors %}
                        <div class="invalid-feedback">
                            {{ error }}
                        </div>
                    {% endfor %}
                {% else %}
                    {% render_field field class="form-control is-valid" %}
                {% endif %}
            {% else %}
                {% render_field field class="form-control" %}
            {% endif %}

            {% if field.help_text %}
                <small class="form-text text-muted">{{ field.help_text }}</small>
            {% endif %}
        </div>
    {% endfor %} 
    <button type="submit" class="btn btn-outline-success my-2 my-sm-0">{{ submit_btn_text }}</button>
</form>

maxblog/templates/posts/base.html
{% extends 'base.html' %}

{% block navbar_list_items %}
<li class="nav-item active">
    <a class="nav-link" href="{% url 'posts:post_new' %}">New post<span class="sr-only">(current)</span></a>
</li>
{% endblock navbar_list_items %}

{% block navbar_content %}
<form action="{% url 'posts:search_posts' %}" class="form-inline my-2 my-lg-0">
    <input name="q" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form>
{% endblock navbar_content %}

maxblog/templates/posts/post_details.html
{% extends 'posts/base.html' %}

{% load widget_tweaks %}
{% load static %}

{% block title %}
{{ post.title }}
{% endblock title %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'posts/css/posts.css' %}">
<div style="padding: 32px; padding-top: 16px;">
    <div class="blog-post">
        <h2 class="blog-post-title">{{ post.title }}</h2>
        {% include 'posts/post_meta.html' %}
        <p>{{ post.text|linebreaksbr }}</p>
    </div>
    <p>
        <em>
            Tags: {% for tag in post.tags.all %}
                <a href="{% url 'posts:search_posts' %}?tag={{ tag.name }}">{{ tag.name }}</a>{% if not forloop.last %}, {% endif %}
            {% endfor %}
        </em>
    </p>
    {% if comments %}
        <h4><em>Comments:</em></h4>
        {% for comment in comments %}
            <div>
                <em>{{ comment.author_name }}</em>
                <p class="post-comment-text">{{ comment.text }}</p>
            </div>
        {% endfor %}
    {% else %}
        <h4><em>There is no comments. You can be the first!</em></h4>
    {% endif %}
    {% with submit_btn_text="Send comment" %}
        {% include 'form.html' %}
    {% endwith %}
</div>
{% endblock %}

maxblog/templates/posts/post_list.html
{% extends 'posts/base.html' %}

{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'posts/css/posts.css' %}">
<div class="blog-main" style="padding-top: 16px;">
    {% for post in object_list %}
    <div class="blog-post" style="padding-left: 32px;">
        <h3 class="blog-post-title"><a href="{% url 'posts:post_details' pk=post.pk %}">{{ post.title }}</a></h3>
        {% include 'posts/post_meta.html' %}
        <p>{{ post.text|truncatechars:500 }}</p>
    </div>
    <hr>
    {% empty %}
        <h1 class="mt-5 container">There are no posts yet. You can <a href="{% url 'posts:post_new' %}">create</a> the first one!</h1>
    {% endfor %}
</div>
{% endblock %}

maxblog/templates/posts/post_meta.html
<p class="blog-post-meta">
    {{ post.created_date|date:'F d, y' }} by
    {% for author in post.authors.all %}
        <a href="{% url 'posts:search_posts' %}?author={{ author.name }}">{{ author.name }}</a>{% if not forloop.last %}, {% endif %}
    {% endfor %}
    in <a href="{% url 'posts:search_posts' %}?section={{ post.section }}">{{ post.section }}</a>
</p>

maxblog/templates/posts/post_new.html
{% extends 'posts/base.html' %}

{% load widget_tweaks %}

{% block title %}Create new post{% endblock title %}

{% block content %}
<div style="padding: 32px; padding-top: 16px;">
    {% with submit_btn_text="Create post" %}
        {% include 'form.html' %}
    {% endwith %}
</div>
{% endblock %}